export const counterReducerActionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET"
}

export const counterSagaActionTypes = {
  ASYNC_INCREMENT: "ASYNC_INCREMENT",
  ASYNC_DECREMENT: "ASYNC_DECREMENT",
  IMMEDIATE_INCREMENT: "IMMEDIATE_INCREMENT",
  IMMEDIATE_DECREMENT: "IMMEDIATE_DECREMENT"
};
