export const counterActionTypes = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
  ASYNC_INCREMENT: "ASYNC_INCREMENT",
  ASYNC_DECREMENT: "ASYNC_DECREMENT",
  IMMEDIATE_INCREMENT: "IMMEDIATE_INCREMENT",
  IMMEDIATE_DECREMENT: "IMMEDIATE_DECREMENT",
};
